name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Correct the checkout path to the CoreTests directory
          path: Test/iOS/CoreTests

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            Test/iOS/CoreTests/Pods
          key: ${{ runner.os }}-build-${{ hashFiles('Test/iOS/CoreTests/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Pods
        # Specify the working directory for pod install
        run: pod install
        working-directory: Test/iOS/CoreTests

      - name: Build the Project
        run: xcodebuild -workspace "CoreTests.xcworkspace" -scheme "CoreTests" -configuration "Release" build
        working-directory: Test/iOS/CoreTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
