name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: NewRelicVideoCore  # Target the NewRelicVideoCore directory

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            NewRelicVideoCore/Pods  # Update the path
          key: ${{ runner.os }}-build-${{ hashFiles('NewRelicVideoCore/Podfile.lock') }}  # Update the key
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Pods
        run: pod install
        working-directory: NewRelicVideoCore  # Update the working directory

      - name: Build the Project
        run: xcodebuild -workspace "NewRelicVideoCore.xcworkspace" -scheme "iOS NewRelicVideoCore" -configuration "Release" build  # Replace with actual workspace and scheme names if necessary
        working-directory: NewRelicVideoCore  # Update the working directory

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
